# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: archlinux/base
      env:
        CI_ROOT_PASSWORD: ${{ secrets.CI_ROOT_PASSWORD }}
        CI_USER_PASSWORD: ${{ secrets.CI_USER_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: requirement
      run: pacman -Sy git
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        ./build-stag1-root.sh
        ./.ci/test-docker.sh
